#!/bin/bash
# Standalone installation script for org-roam-ai MCP server
# Installs everything needed for the MCP server to run independently

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
VENV_DIR="$HOME/.org-roam-mcp"
SERVICE_NAME="org-roam-mcp"
GITEA_URL="https://gitea-backend.cruver.network/dcruver/org-roam-ai"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}org-roam-ai MCP Server Installation${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Function to check prerequisites
check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    local missing=0

    # Check Python 3
    if ! command -v python3 >/dev/null 2>&1; then
        echo -e "${RED}✗ Python 3 not found${NC}"
        echo "  Please install Python 3.8+ first"
        missing=1
    else
        echo -e "${GREEN}✓ Python 3 found${NC}"
    fi

    # Check pip
    if ! command -v pip3 >/dev/null 2>&1; then
        echo -e "${RED}✗ pip3 not found${NC}"
        echo "  Please install pip3 first"
        missing=1
    else
        echo -e "${GREEN}✓ pip3 found${NC}"
    fi

    # Check Emacs
    if ! command -v emacs >/dev/null 2>&1; then
        echo -e "${RED}✗ Emacs not found${NC}"
        echo "  Please install Emacs first"
        missing=1
    else
        echo -e "${GREEN}✓ Emacs found${NC}"
    fi

    # Check straight.el
    if ! emacs --batch --eval "(require 'straight nil t)" >/dev/null 2>&1; then
        echo -e "${RED}✗ straight.el not found${NC}"
        echo "  Please install straight.el first:"
        echo "  curl -fsSL https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el | emacs --batch -l /dev/stdin"
        echo "  Then re-run this installation script."
        missing=1
    else
        echo -e "${GREEN}✓ straight.el found${NC}"
    fi

    # Check if Emacs server is running
    if ! emacsclient --eval '(+ 1 1)' >/dev/null 2>&1; then
        echo -e "${YELLOW}⚠ Emacs server not running${NC}"
        echo "  The MCP server will start it automatically"
    else
        echo -e "${GREEN}✓ Emacs server running${NC}"
    fi

    if [ $missing -eq 1 ]; then
        echo -e "${RED}Missing prerequisites. Please install them and re-run this script.${NC}"
        exit 1
    fi

    echo ""
}

# Function to setup Python virtual environment
setup_venv() {
    echo -e "${YELLOW}Setting up Python virtual environment...${NC}"

    if [ -d "$VENV_DIR" ]; then
        echo -e "${YELLOW}Virtual environment already exists. Updating...${NC}"
        source "$VENV_DIR/bin/activate"
        pip install --upgrade pip
    else
        echo -e "${YELLOW}Creating virtual environment...${NC}"
        python3 -m venv "$VENV_DIR"
        source "$VENV_DIR/bin/activate"
        pip install --upgrade pip
    fi

    echo -e "${GREEN}✓ Virtual environment ready${NC}"
    echo ""
}

# Function to install MCP server
install_mcp() {
    echo -e "${YELLOW}Installing MCP server...${NC}"

    source "$VENV_DIR/bin/activate"

    # Install from PyPI
    pip install --upgrade org-roam-mcp

    if command -v org-roam-mcp >/dev/null 2>&1; then
        echo -e "${GREEN}✓ MCP server installed successfully${NC}"
    else
        echo -e "${RED}✗ MCP server installation failed${NC}"
        exit 1
    fi

    echo ""
}

# Function to setup Emacs configuration for org-roam packages
setup_emacs_config() {
    echo -e "${YELLOW}Setting up Emacs configuration for org-roam packages...${NC}"

    CONFIG_FILE="$HOME/.emacs.d/init-org-roam-mcp.el"

    # Create configuration file for MCP-required packages
    cat > "$CONFIG_FILE" << 'EOF'
;; Configuration for org-roam MCP server packages
;; This file is automatically generated by the MCP installer

;; Bootstrap straight.el if not already done
(unless (featurep 'straight)
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))

;; Install required packages
(straight-use-package
  '(org-roam-vector-search
    :type git
    :host github
    :repo "dcruver/org-roam-ai"
    :files ("packages/org-roam-ai/org-roam-vector-search.el")))

(straight-use-package
  '(org-roam-ai-assistant
    :type git
    :host github
    :repo "dcruver/org-roam-ai"
    :files ("packages/org-roam-ai/org-roam-ai-assistant.el")))

(straight-use-package
  '(org-roam-api
    :type git
    :host github
    :repo "dcruver/org-roam-ai"
    :files ("packages/org-roam-ai/org-roam-api.el")))

;; Load org-roam if available
(when (require 'org-roam nil t)
  (org-roam-db-autosync-mode))
EOF

    # Add Ollama URL configuration if environment variable is set
    if [ -n "$OLLAMA_URL" ]; then
        echo -e "${YELLOW}Configuring Ollama URL: $OLLAMA_URL${NC}"
        cat >> "$CONFIG_FILE" << EOF

;; Configure Ollama URL
(customize-set-variable 'org-roam-semantic-ollama-url "$OLLAMA_URL")
EOF
    fi

    # Add embedding model configuration if environment variable is set
    if [ -n "$OLLAMA_EMBEDDING_MODEL" ]; then
        echo -e "${YELLOW}Configuring embedding model: $OLLAMA_EMBEDDING_MODEL${NC}"
        cat >> "$CONFIG_FILE" << EOF
(customize-set-variable 'org-roam-semantic-embedding-model "$OLLAMA_EMBEDDING_MODEL")
EOF
    fi

    # Add generation model configuration if environment variable is set
    if [ -n "$OLLAMA_GENERATION_MODEL" ]; then
        echo -e "${YELLOW}Configuring generation model: $OLLAMA_GENERATION_MODEL${NC}"
        cat >> "$CONFIG_FILE" << EOF
(customize-set-variable 'org-roam-semantic-generation-model "$OLLAMA_GENERATION_MODEL")
EOF
    fi

    # Add chunking configuration if environment variable is set
    if [ -n "$ENABLE_CHUNKING" ]; then
        echo -e "${YELLOW}Configuring chunking: $ENABLE_CHUNKING${NC}"
        cat >> "$CONFIG_FILE" << EOF
(customize-set-variable 'org-roam-semantic-enable-chunking t)
EOF
    fi

    # Add minimum chunk size configuration if environment variable is set
    if [ -n "$MIN_CHUNK_SIZE" ]; then
        echo -e "${YELLOW}Configuring minimum chunk size: $MIN_CHUNK_SIZE${NC}"
        cat >> "$CONFIG_FILE" << EOF
(customize-set-variable 'org-roam-semantic-min-chunk-size $MIN_CHUNK_SIZE)
EOF
    fi

    # Check if init.el already loads this file
    if ! grep -q "init-org-roam-mcp.el" "$HOME/.emacs.d/init.el" 2>/dev/null; then
        echo -e "${YELLOW}Adding MCP config to init.el...${NC}"
        echo "(load \"~/.emacs.d/init-org-roam-mcp.el\")" >> "$HOME/.emacs.d/init.el"
    fi

    echo -e "${GREEN}✓ Emacs configuration set up${NC}"
    echo ""
}

# Function to create systemd service
create_service() {
    echo -e "${YELLOW}Creating systemd service...${NC}"

    sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null <<EOF
[Unit]
Description=Org-roam MCP Server
After=network.target

[Service]
Type=simple
User=$USER
Group=$USER
Environment=PATH=$VENV_DIR/bin:/usr/local/bin:/usr/bin
Environment=EMACS_SERVER_FILE=$HOME/.emacs.d/server/server
ExecStart=$VENV_DIR/bin/org-roam-mcp
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    echo -e "${GREEN}✓ Created ${SERVICE_NAME}.service${NC}"
    echo ""
}

# Function to enable service
enable_service() {
    echo -e "${YELLOW}Enabling systemd service...${NC}"

    sudo systemctl daemon-reload
    sudo systemctl enable ${SERVICE_NAME}.service

    echo -e "${GREEN}✓ Service enabled${NC}"
    echo ""
}

# Main installation
main() {
    check_prerequisites
    setup_venv
    install_mcp
    setup_emacs_config
    create_service
    enable_service

    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}Installation complete!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo ""
    echo "1. Start the service:"
    echo "   sudo systemctl start ${SERVICE_NAME}.service"
    echo ""
    echo "2. Check service status:"
    echo "   sudo systemctl status ${SERVICE_NAME}.service"
    echo ""
    echo "3. View logs:"
    echo "   sudo journalctl -u ${SERVICE_NAME}.service -f"
    echo ""
    echo -e "${YELLOW}Configuration:${NC}"
    echo "  MCP Server: http://localhost:8000"
    echo "  Virtual Environment: ${VENV_DIR}"
    echo "  Service: ${SERVICE_NAME}.service"
    echo ""
    echo -e "${GREEN}The MCP server will automatically install required Emacs packages on first run!${NC}"
    echo ""
}

# Run main installation
main